baseURL = 'dpak94.github.io/notes'
languageCode = 'en-us'
title = 'Web Notes'
theme = 'hugo-book'

bookTheme = 'auto'
BookToc = true
BookLogo = 'otter-kid.jpeg'
# BookMenuBundle = '/menu'
BookSection = 'docs'
BookRepo = 'https://github.com/alex-shpak/hugo-book'
BookSearch = true
BookComments = true